[versions]
coroutines = "1.10.2"
kotlin = "2.2.21"
arrow = "2.2.0"
springboot = "4.0.0"
spotless = "8.1.0"
java = "17"
kotlinxSerialization = "1.9.0"
ktlint = "0.50.0"
nimbusJoseJwt = "10.6"
nimbusOAuth2 = "11.30.1"
eudiSdJwt = "0.17.1"
bouncyCastle = "1.82"
dependencyCheck = "12.1.9"
bootstrap = "5.3.8"
multiformat = "1.1.0"
resultMonad = "1.4.0"
waltid = "1.13.0"
uri-kmp = "0.0.21"
zxing = "3.5.4"
tink = "1.19.0"
kover = "0.9.3"
cose-java = "1.1.0"
kotlinx-datetime = "0.7.1-0.6.x-compat"

[libraries]
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
arrow-fx-coroutines = { module = "io.arrow-kt:arrow-fx-coroutines", version.ref = "arrow" }
nimbus-jose-jwt = { module = "com.nimbusds:nimbus-jose-jwt", version.ref = "nimbusJoseJwt" }
nimbus-oauth2 = { module = "com.nimbusds:oauth2-oidc-sdk", version.ref = "nimbusOAuth2" }
eudi-sdjwt = { module = "eu.europa.ec.eudi:eudi-lib-jvm-sdjwt-kt", version.ref = "eudiSdJwt" }
bouncy-castle = { module = "org.bouncycastle:bcpkix-jdk18on", version.ref = "bouncyCastle" }
bootstrap = { module = "org.webjars:bootstrap", version.ref = "bootstrap" }
tink = { module = "com.google.crypto.tink:tink", version.ref = "tink" }
multiformat = { module = "org.erwinkok.multiformat:multiformat", version.ref = "multiformat" }
result-monad = { module = "org.erwinkok.result:result-monad", version.ref = "resultMonad" }
waltid-mdoc-credentials = { module = "id.walt.mdoc-credentials:waltid-mdoc-credentials-jvm", version.ref = "waltid" }
uri-kmp = { module = "com.eygraber:uri-kmp", version.ref = "uri-kmp" }
zxing = { module = "com.google.zxing:javase", version.ref = "zxing" }
cose-java = { module = "com.augustcellars.cose:cose-java", version.ref = "cose-java" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springboot" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-plugin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
dependency-check = { id = "org.owasp.dependencycheck", version.ref = "dependencyCheck" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }

