[versions]
coroutines = "1.8.1"
kotlin = "2.0.0"
arrow = "1.2.4"
foojay = "0.8.0"
springboot = "3.2.5"
springDependencyManagement = "1.1.5"
spotless = "6.25.0"
java = "17"
kotlinxSerialization = "1.6.3"
ktlint = "0.50.0"
nimbusJoseJwt = "9.39.1"
nimbusOAuth2 = "11.12"
eudiSdJwt = "0.4.0"
bouncyCastle = "1.78.1"
dependencyCheck = "9.2.0"
sonarqube = "5.0.0.4638"
bootstrap = "5.3.3"
qrgen = "3.0.1"
jacoco = "0.8.11"
didCommon = "1.13.0"
multiformat = "1.1.0"
resultMonad = "1.4.0"
keycloak = "24.0.4"
waltid = "1.0.2405210855-SNAPSHOT"
uri-kmp = "0.0.18"

[libraries]
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlinx-serialization-cbor = { module = "org.jetbrains.kotlinx:kotlinx-serialization-cbor", version.ref = "kotlinxSerialization" }
arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
arrow-fx-coroutines = { module = "io.arrow-kt:arrow-fx-coroutines", version.ref = "arrow" }
nimbus-jose-jwt = { module = "com.nimbusds:nimbus-jose-jwt", version.ref = "nimbusJoseJwt" }
nimbus-oauth2 = { module = "com.nimbusds:oauth2-oidc-sdk", version.ref = "nimbusOAuth2" }
eudi-sdjwt = { module = "eu.europa.ec.eudi:eudi-lib-jvm-sdjwt-kt", version.ref = "eudiSdJwt" }
bouncy-castle = { module = "org.bouncycastle:bcpkix-jdk18on", version.ref = "bouncyCastle" }
bootstrap = { module = "org.webjars:bootstrap", version.ref = "bootstrap" }
qrgen = { module = "com.github.kenglxn.QRGen:javase", version.ref = "qrgen" }
did-common = { module = "decentralized-identity:did-common-java", version.ref = "didCommon" }
multiformat = { module = "org.erwinkok.multiformat:multiformat", version.ref = "multiformat" }
result-monad = { module = "org.erwinkok.result:result-monad", version.ref = "resultMonad" }
keycloak-admin-client = { module = "org.keycloak:keycloak-admin-client", version.ref = "keycloak" }
waltid-mdoc-credentials = { module = "id.walt:waltid-mdoc-credentials-jvm", version.ref = "waltid" }
uri-kmp = { module = "com.eygraber:uri-kmp", version.ref = "uri-kmp" }

[plugins]
foojay-resolver-convention = { id = "org.gradle.toolchains.foojay-resolver-convention", version.ref = "foojay" }
spring-boot = { id = "org.springframework.boot", version.ref = "springboot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-plugin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
dependency-check = { id = "org.owasp.dependencycheck", version.ref = "dependencyCheck" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }
